//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class bs_ClientLimits
    {
        public int CLID { get; set; }
        public int ClientID { get; set; }
        public int ProductID { get; set; }
        public decimal LimitValue { get; set; }
        public int CCYID { get; set; }
    
        public virtual bs_ClientProducts bs_ClientProducts { get; set; }
        public virtual Clients bs_Clients { get; set; }
    }
}
