//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ActivitiesEntities : DbContext
    {
        public ActivitiesEntities()
            : base("name=ActivitiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bs_ClientEntities> bs_ClientEntities { get; set; }
        public virtual DbSet<bs_ClientEntityLimits> bs_ClientEntityLimits { get; set; }
        public virtual DbSet<bs_ClientLimits> bs_ClientLimits { get; set; }
        public virtual DbSet<bs_ClientProducts> bs_ClientProducts { get; set; }
        public virtual DbSet<Clients> bs_Clients { get; set; }
        public virtual DbSet<Sector_Bank> bs_SectorBank { get; set; }
        public virtual DbSet<bs_SectorOKVED> bs_SectorOKVED { get; set; }
    }
}
