//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector_Bank
    {
        public Sector_Bank()
        {
            this.bs_Clients = new HashSet<Clients>();
        }
    
        public int SectorBankID { get; set; }
        public string SectorBankName { get; set; }
        public Nullable<int> GICSSubindustryID { get; set; }
        public Nullable<int> SectorOKVEDID { get; set; }
    
        public virtual ICollection<Clients> bs_Clients { get; set; }
    }
}
