//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bs_ClientMeetings
    {
        public int ClientMtgID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> ClientEntityID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Subject { get; set; }
        public string RM { get; set; }
        public string Contacts { get; set; }
        public string Results { get; set; }
        public string Questions { get; set; }
    
        public virtual bs_ClientEntities bs_ClientEntities { get; set; }
        public virtual bs_Clients bs_Clients { get; set; }
    }
}
