//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bs_ClientEntities
    {
        public bs_ClientEntities()
        {
            this.bs_ClientEntityLimits = new HashSet<bs_ClientEntityLimits>();
            this.bs_ClientMeetings = new HashSet<bs_ClientMeetings>();
        }
    
        public int ClientEntityID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string EntityName { get; set; }
        public int SectorBankID { get; set; }
        public Nullable<int> SectorOKVEDID { get; set; }
    
        public virtual ICollection<bs_ClientEntityLimits> bs_ClientEntityLimits { get; set; }
        public virtual ICollection<bs_ClientMeetings> bs_ClientMeetings { get; set; }
    }
}
