//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bs_Clients
    {
        public bs_Clients()
        {
            this.bs_ClientEntityLimits = new HashSet<bs_ClientEntityLimits>();
            this.bs_ClientFTPRates = new HashSet<bs_ClientFTPRates>();
            this.bs_ClientMeetings = new HashSet<bs_ClientMeetings>();
        }
    
        public int ClientID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PrimaryContact { get; set; }
        public Nullable<int> CountryOfRiskID { get; set; }
        public Nullable<int> GICSSubIndustryID { get; set; }
        public int SectorBankID { get; set; }
        public int SectorOKVEDID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual ICollection<bs_ClientEntityLimits> bs_ClientEntityLimits { get; set; }
        public virtual ICollection<bs_ClientFTPRates> bs_ClientFTPRates { get; set; }
        public virtual ICollection<bs_ClientMeetings> bs_ClientMeetings { get; set; }
        public virtual bs_SectorBank bs_SectorBank { get; set; }
        public virtual bs_SectorOKVED bs_SectorOKVED { get; set; }
    }
}
