//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bs_GICSMap
    {
        public int GICSSubindustryID { get; set; }
        public string SectorCode { get; set; }
        public string SectorName { get; set; }
        public string IndustryGroupCode { get; set; }
        public string IndustryGroupName { get; set; }
        public string IndustryCode { get; set; }
        public string IndustryName { get; set; }
        public string SubindustryCode { get; set; }
        public string SubindustryName { get; set; }
    }
}
